### ISSUE TITLE
Vertical swipes are blocked on my sliders

### ISSUE THREAD

**Issue by kevrmnd** [armandsalle/butter-slider#53]
Hey, first of all : thank you for the lib, it rocks 👍 

i have an issue on all my sliders : I can't swipe vertically on them. That mean I can't scroll through my page when my thumb is on a butter slider, I am forced to scroll from the outside of the butter slider. Do I do something wrong or is it something you want in the butter slider ?

Thanks

**Comment by armandsalle** [comment]
Hey! Thank you for your words ❤️

Yes I noticed that while I was coding BS so I added the `hasTouchEvent` parameter to kill the BS effect and let the native scroll do the job. It's not the best solution but I never took the time to deep dive into touch events for sliders.

Also, I recommend that you do not use BS because it is no longer maintained.
